services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    command: >
      postgres -c log_statement=all
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
      # logs into container: /var/lib/postgresql/data/log
      - postgres_data:/var/lib/postgresql/data

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    environment:
      DYNAMODB_LOCAL_LOG_LEVEL: DEBUG
    ports:
      - 8000:8000

volumes:
  postgres_data:
